In [25]:
import numpy as np
import pandas as pd

In [54]:
#1
a=np.zeros(10)
a[4]=1
print('Task1:\n', a)

#2
b=np.arange(10,50)
print('Task2:\n', b)

#3
c=b[::-1]
print('Task3:\n', c)

#4
d=np.arange(9).reshape(3,3)
print('Task4:\n', d)

#5
e=np.nonzero([1,2,0,0,4,0])
print('Task5:\n', e)

#6
f=np.random.random((3,3,3))
print('Task6:\n', f)

#7
g=np.random.random((10,10))
gmin=g.min()
gmax=g.max()
print('Task7:\n','Min: ', gmin,'Max: ', gmax)

#8 
h=np.random.random(30)
hmean=h.mean()
print('Task8:\n', hmean)

#9
i=np.random.random((3,3))
iborder = np.pad(i, pad_width=1, mode='constant', constant_values=0)
print('Task9:\n', iborder)

#10
j=np.zeros((8,8))
j[1::2,::2]=1
j[::2,1::2]=1
print('Task10:\n', j)

#11
k=np.random.random((5,5))
kmin=np.min(k)
kmax=np.max(k)
k=(k-kmin)/(kmax-kmin)
print('Task11:\n', k)

#12
l=np.arange(10)
l=np.where((l>3) & (l<8) ,l*-1,l)
print('Task12:\n', l)

#13m
m=[2,3,4,6,8,0]
n=[3,9,11,8,0,7]
intersec=np.intersect1d(m,n)
print('Task13:\n', intersec)

#14
o=np.zeros((5,5))
o+=np.arange(5)
print('Task14:\n', o)

#15
p=np.random.random(10)
p=np.where(p==0,p+0.01,p)
print('Task15:\n', p)

Task1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Task2:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Task3:
 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
Task4:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Task5:
 (array([0, 1, 4], dtype=int64),)
Task6:
 [[[0.08860649 0.06552676 0.64319997]
  [0.32219047 0.70868234 0.58084094]
  [0.7417518  0.31977409 0.72590436]]

 [[0.16153898 0.05497658 0.5684266 ]
  [0.67822204 0.3691021  0.30886812]
  [0.50643013 0.92600303 0.26083559]]

 [[0.81168171 0.58660614 0.55456792]
  [0.93648425 0.35036708 0.84397873]
  [0.50339196 0.17451451 0.06729316]]]
Task7:
 Min:  0.00663313330980464 Max:  0.9751106547723766
Task8:
 0.5270691435363825
Task9:
 [[0.         0.         0.         0.         0.        ]
 [0.         0.70201981 0.06301196 0.99612982 0.        ]
 [0.         0.07644458 0.74975148 0.02154591 0.        ]
 [0.  