In [16]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [2]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [4]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [6]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.4276456  0.44316376 0.30381797]
  [0.00174463 0.84101086 0.61834781]
  [0.78307338 0.33742112 0.40652721]]

 [[0.78004493 0.2271294  0.49280055]
  [0.47713901 0.69217744 0.08826474]
  [0.46504336 0.36400734 0.66037205]]

 [[0.45919657 0.2238766  0.63749499]
  [0.53707663 0.66589341 0.9527631 ]
  [0.86958201 0.58512471 0.93789605]]]


In [7]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.019714577735186034 0.9913422270587662


In [20]:
Z = np.random.random(30)
#print(Z)
m = Z.mean()
print(m)

0.5109264608064508


In [9]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [22]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [24]:
Z = np.random.random((5,5))
#print(np.std (Z))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 1.21385738  0.08152675 -1.12800187 -0.82192316 -0.87900042]
 [-1.06523008  1.39867456  1.29007463  1.28939896  1.32336508]
 [-1.25308756 -0.22171132 -1.09211066 -0.32038807  1.00283239]
 [ 0.70474842  1.21190594  1.29936824 -0.91468189 -0.23535878]
 [-0.39801764 -0.66357321  0.55456446 -0.72381756 -1.65341456]]


In [12]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)



[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [25]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))

[8 2 6 4 1 7 5 8 8 8]
[2 4 5 5 9 3 6 9 1 8]
[1 2 4 5 6 8]


In [14]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [29]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
