In [3]:
#Slyamkhan Kuanysh
import numpy as np

In [24]:
#1
arr1=np.zeros([10])
arr1[5]=1
arr1

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [27]:
#2
arr2=np.array([range(10,50)])
arr2

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
        26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49]])

In [32]:
#3
arr3=np.array([range(1,10)])
np.flip(arr3)

array([[9, 8, 7, 6, 5, 4, 3, 2, 1]])

In [35]:
#4
arr4=np.array([[0,1,2],[3,4,5],[6,7,8]])
arr4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
#5
arr5=np.array([1,2,0,0,4,0])
for i in range(len(arr5)):
    if arr5[i]!=0:
        print(i)

0
1
4


In [63]:
#6
import random
arr6=np.array([random.random() for r in range(0,27)]).reshape(3,3,3)
arr6

array([[[0.2309653 , 0.42821826, 0.55456835],
        [0.98560927, 0.65589418, 0.4083683 ],
        [0.75592021, 0.20230699, 0.78203985]],

       [[0.48495699, 0.26648847, 0.86317869],
        [0.91364697, 0.64040916, 0.18255714],
        [0.63308214, 0.33389743, 0.95563386]],

       [[0.08647561, 0.79223542, 0.92620542],
        [0.63370106, 0.01134445, 0.32016984],
        [0.59025668, 0.45391929, 0.65088648]]])

In [63]:
#7
import random
arr7=np.array([int(random.random()*100) for r in range(0,100)]).reshape(10,10)
minimum=9999999
maximum=0
for j in arr7:
    for i in j:
        if i<=minimum:
            minimum=i
        if i>=maximum:
            maximum=i
print(minimum,maximum)
print(arr7.min(), arr7.max())

1 98
1 98


In [34]:
#8
arr8=np.array([int(random.random()*100) for r in range(0,30)])
print(arr8)
summ=0
for i in arr8:
    summ+=i
mean=summ/len(arr8)
mean

[42 25 95 71 83 85 23 66 49 81 33 63 40 86 84 49 56 18 32 62 63 41 85 72
 28 68 53 21 64 19]


55.233333333333334

In [36]:
#9
arr9 = np.ones((3,3))
print(arr9)
print()
arr9_1 = np.pad(arr9, pad_width=1, mode='constant', constant_values=0)
print(arr9_1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [59]:
#10
arr10=np.ones([8,8])
for i in range(len(arr10)):
    #print(arr10[i])
    for j in range(len(arr10[i])):
        if j%2==0 and i%2==1:
            arr10[i][j]=0
        if j%2==1 and i%2==0:
            arr10[i][j]=0

arr10

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [72]:
#11
arr11=np.random.random([5,5])
arrmax, arrmin = arr11.max(), arr11.min()
arr11_1 = (arr11 - arrmin)/(arrmax - arrmin)
print(arr11_1)

[[0.99968554 0.30118814 0.40206466 1.         0.48091116]
 [0.91965602 0.9035679  0.32091063 0.24550299 0.42849338]
 [0.508591   0.43851425 0.49040631 0.55865469 0.43269284]
 [0.72679554 0.81938716 0.29621123 0.26024273 0.85202698]
 [0.         0.06125474 0.99339401 0.63177768 0.38599131]]


In [97]:
#12
arr12=np.arange(0,11)
m = (arr12 > 2) & (arr12 < 8)
arr12[m] *= -1
arr12

array([ 0,  1,  2, -3, -4, -5, -6, -7,  8,  9, 10])

In [82]:
#13
arr13_1=np.array([int(random.random()*10) for r in range(0,5)])
arr13_2=np.array([int(random.random()*10) for r in range(0,5)])
print(arr13_1)
print(arr13_2)
print(np.intersect1d(arr13_1,arr13_2))

[1 8 9 3 6]
[1 6 1 3 0]
[1 3 6]


In [94]:
#14
arr14=np.zeros([5,5])
arr14 += np.arange(5)
arr14

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [101]:
#15
arr15=np.linspace(0,1,12,endpoint=True)[1:-1]
arr15

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])