In [36]:
import numpy as np

In [37]:
#1
a = np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [38]:
#2
a = np.arange(10,49)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [39]:
#3
a = np.arange(0,10)
print(a)
print(a[::-1])

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [40]:
#4
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [41]:
#5
print(np.nonzero([1,2,0,0,4,0]))

(array([0, 1, 4], dtype=int64),)


In [42]:
#6
print(np.random.randint(10, size=(3,3,3)))

[[[6 4 3]
  [2 8 3]
  [6 5 9]]

 [[1 9 5]
  [6 7 4]
  [3 9 9]]

 [[9 6 2]
  [4 7 2]
  [0 9 2]]]


In [43]:
#7
a = np.random.random((5,5))
print(a.min(), a.max())

0.006901188752350906 0.9846133930176618


In [44]:
#8
a = np.random.random(30)
a.mean()

0.5054733721187085

In [45]:
#9
a = np.ones((3,3))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [46]:
#10
a = np.zeros((8,8),dtype=int)
a[1::2,::2]=1
a[::2,1::2]=1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [47]:
#11
x = np.random.randint(10, size=(5,5))
print(x)
x = (x - x.min())/(x.max() - x.min())
print(x)

[[0 7 5 2 2]
 [2 8 6 4 3]
 [4 9 7 2 0]
 [6 4 1 2 6]
 [3 0 1 0 4]]
[[0.         0.77777778 0.55555556 0.22222222 0.22222222]
 [0.22222222 0.88888889 0.66666667 0.44444444 0.33333333]
 [0.44444444 1.         0.77777778 0.22222222 0.        ]
 [0.66666667 0.44444444 0.11111111 0.22222222 0.66666667]
 [0.33333333 0.         0.11111111 0.         0.44444444]]


In [23]:
#12
a = np.arange(11)
a[(3 < a) & (a <= 8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [35]:
#13
a = np.array([0, 10, 20, 40, 60])
b = np.array([10, 30, 40])
print(np.intersect1d(a, b))

[10 40]


In [34]:
#14
a = np.zeros((5,5))
print(a)
a += np.arange(5)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [33]:
#15
a = np.linspace(0,1,11,endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
