In [2]:
from numpy import *


In [3]:
b = array([1, 2, 3, 4])
b

array([1, 2, 3, 4])

In [4]:
b = zeros(10)
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
b[4] = 1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [6]:
a = arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
a = array([1, 2, 3, 4, 5, 6, 7, 8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
b = a[::-1]
b

array([8, 7, 6, 5, 4, 3, 2, 1])

In [9]:
a = arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
a = a.reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
a = [1,2,0,0,4,0]
a

[1, 2, 0, 0, 4, 0]

In [12]:
b = nonzero(a)
b

(array([0, 1, 4], dtype=int64),)

In [13]:
a = random.rand(3, 3, 3)
a

array([[[0.94606689, 0.33715187, 0.56028469],
        [0.04971919, 0.69380262, 0.78245321],
        [0.89071888, 0.37623643, 0.40888065]],

       [[0.43827197, 0.12465779, 0.93293019],
        [0.23524022, 0.75029148, 0.8127153 ],
        [0.04978274, 0.08489464, 0.49667845]],

       [[0.50993351, 0.96560275, 0.70491546],
        [0.77926654, 0.74015707, 0.7058869 ],
        [0.10126244, 0.34052613, 0.44537067]]])

In [14]:
a = random.rand(10, 10)
a

array([[0.78262921, 0.46238069, 0.36373332, 0.61644448, 0.06689384,
        0.03953092, 0.43572995, 0.9832708 , 0.6295381 , 0.93726044],
       [0.45699114, 0.05459231, 0.65740566, 0.25995498, 0.55850445,
        0.30523695, 0.23333452, 0.76451259, 0.28117305, 0.4328837 ],
       [0.09607202, 0.20585456, 0.76741251, 0.67354564, 0.00243463,
        0.17263463, 0.67633166, 0.17513258, 0.52083874, 0.49743927],
       [0.6578934 , 0.04456474, 0.73986814, 0.96227175, 0.41179062,
        0.75588924, 0.08818662, 0.32590062, 0.57670401, 0.26976488],
       [0.18068147, 0.85610317, 0.46242158, 0.96049   , 0.81045993,
        0.1222062 , 0.535132  , 0.41268318, 0.42060875, 0.17576505],
       [0.6447361 , 0.96402149, 0.39346908, 0.99806857, 0.20788737,
        0.62074264, 0.43924534, 0.75548731, 0.60057846, 0.3003159 ],
       [0.80956814, 0.85828923, 0.27652732, 0.97111084, 0.4721851 ,
        0.60674111, 0.98883527, 0.5801899 , 0.26864292, 0.33656449],
       [0.83330812, 0.42300306, 0.9712715

In [15]:
m = amax(a)
m

0.9980685686412049

In [16]:
n = amin(a)
n

0.002434632929560143

In [17]:
a = random.rand(30)
a

array([0.18997519, 0.02270293, 0.98540466, 0.72674691, 0.46340432,
       0.72755685, 0.2064241 , 0.76318287, 0.20527227, 0.78383385,
       0.14899397, 0.99039774, 0.92552494, 0.99781652, 0.47466326,
       0.17629764, 0.24251774, 0.12632205, 0.39984536, 0.89912908,
       0.73825988, 0.23646253, 0.97034635, 0.31977693, 0.97880904,
       0.9439758 , 0.93079839, 0.42375443, 0.34624058, 0.15363672])

In [18]:
mean = average(a)
mean

0.5499357634341172

In [20]:
def printcheckboard(n): 
      
    x = zeros((n, n), dtype = int) 
    x[1::2, ::2] = 1
    x[::2, 1::2] = 1
      
    for i in range(n): 
        for j in range(n): 
            print(x[i][j], end =" ")  
        print()  
n = 8
printcheckboard(n)

Checkerboard pattern:
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 


In [21]:
x= random.random((5,5))
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print(x)

[[0.29310159 0.85560355 0.16644668 0.53135935 0.55916132]
 [0.77034805 0.30452458 0.18809605 0.22844242 0.46430992]
 [0.5362264  0.0410358  0.07455997 0.33870275 0.26130707]
 [0.30795367 0.44651421 0.39114009 0.6755283  0.43839108]
 [0.61884251 0.         0.81878844 0.11236177 1.        ]]


In [23]:
array1 = [0, 10, 20, 40, 60]

array2 = [10, 30, 40]

print(intersect1d(array1, array2))

[10 40]


In [30]:
a = array([arange(0,5,1), arange(0,5,1), arange(0,5,1), arange(0,5,1), arange(0,5,1)])
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
